version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          command: |
            mkdir test-results
            sudo pip install -r requirements.txt
      - run:
          command: |
            pytest -v --junitxml=test-results/junit.xml
  deploy:
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:4732e5e0-f656-47a5-ada1-b7b4d804bb26@git.heroku.com/some-appp.git master

workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: main # only run deploy-via-git job on main branch
